#!/usr/bin/env python3
"""
Train the MemoryLinker MLP from feedback logs.

Reads training_log.jsonl (generated by session-manager log-feedback),
constructs positive/negative pairs, and trains the linker head on top of
frozen sentence-transformer embeddings.

Usage:
  python train_linker.py <persona_dir> [--epochs 20] [--lr 1e-3] [--min-samples 20]
  python train_linker.py <persona_dir> --info   # Show training data stats without training
"""

import sys
import os
import json
import argparse

import torch
import torch.nn as nn
import numpy as np

# Relative imports
sys.path.insert(0, os.path.dirname(__file__))
from linker import MemoryLinker
from cold_start import initialize_weights


def load_feedback_log(persona_dir):
    """Load and parse training_log.jsonl."""
    log_path = os.path.join(persona_dir, 'logs', 'training_log.jsonl')
    entries = []
    if not os.path.exists(log_path):
        return entries
    with open(log_path, 'r', encoding='utf-8') as f:
        for line in f:
            line = line.strip()
            if line:
                try:
                    entries.append(json.loads(line))
                except json.JSONDecodeError:
                    continue
    return entries


def build_training_pairs(entries, metas, id_to_idx):
    """
    Build (query_text, memory_idx, label) triples from feedback log.

    Positive: memory was retrieved AND used (label=1)
    Negative: memory was retrieved but NOT used (label=0)

    Returns list of (context_text, memory_index, label) tuples.
    """
    pairs = []
    for entry in entries:
        context = entry.get('context_preview', '')
        if not context:
            continue

        positives = entry.get('positive', [])
        negatives = entry.get('negative', [])

        for mem_id in positives:
            idx = id_to_idx.get(mem_id)
            if idx is not None:
                pairs.append((context, idx, 1.0))

        for mem_id in negatives:
            idx = id_to_idx.get(mem_id)
            if idx is not None:
                pairs.append((context, idx, 0.0))

    return pairs


def train(persona_dir, epochs=20, lr=1e-3, min_samples=20):
    """Train the linker from feedback data."""
    import faiss

    # Load FAISS index and metadata
    flat_path = os.path.join(persona_dir, 'index_flat.faiss')
    index_path = os.path.join(persona_dir, 'index.faiss')
    meta_path = os.path.join(persona_dir, 'index_meta.json')

    actual_index_path = flat_path if os.path.exists(flat_path) else index_path
    if not os.path.exists(actual_index_path):
        print(json.dumps({"error": "No FAISS index found. Run embedder.py build first."}))
        sys.exit(1)

    index = faiss.read_index(actual_index_path)
    with open(meta_path, 'r') as f:
        metas = json.load(f)

    id_to_idx = {m['id']: i for i, m in enumerate(metas)}
    n_memories = len(metas)

    # Load feedback log
    entries = load_feedback_log(persona_dir)
    if not entries:
        print(json.dumps({"error": "No feedback data found. Need log-feedback calls first."}))
        sys.exit(1)

    # Build training pairs
    pairs = build_training_pairs(entries, metas, id_to_idx)
    n_pos = sum(1 for _, _, l in pairs if l > 0.5)
    n_neg = len(pairs) - n_pos

    if len(pairs) < min_samples:
        print(json.dumps({
            "error": f"Not enough training data. Have {len(pairs)} pairs, need {min_samples}.",
            "positive": n_pos,
            "negative": n_neg,
            "feedback_entries": len(entries),
        }))
        sys.exit(1)

    print(f"Training data: {len(pairs)} pairs ({n_pos} positive, {n_neg} negative) "
          f"from {len(entries)} feedback entries", file=sys.stderr)

    # Encode contexts
    os.environ.setdefault('CUDA_VISIBLE_DEVICES', '')
    from sentence_transformers import SentenceTransformer
    encoder = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2', device='cpu')

    # Deduplicate contexts for efficient encoding
    unique_contexts = list(set(p[0] for p in pairs))
    context_embs = encoder.encode(unique_contexts, normalize_embeddings=True,
                                  show_progress_bar=True, batch_size=32)
    context_to_emb = {ctx: emb for ctx, emb in zip(unique_contexts, context_embs)}

    # Reconstruct memory embeddings from index
    all_mem_embs = np.array([index.reconstruct(i) for i in range(n_memories)], dtype='float32')

    # Build tensors
    ctx_tensors = []
    mem_tensors = []
    labels = []
    for ctx, mem_idx, label in pairs:
        ctx_tensors.append(context_to_emb[ctx])
        mem_tensors.append(all_mem_embs[mem_idx])
        labels.append(label)

    ctx_tensor = torch.tensor(np.array(ctx_tensors), dtype=torch.float32)
    mem_tensor = torch.tensor(np.array(mem_tensors), dtype=torch.float32)
    label_tensor = torch.tensor(labels, dtype=torch.float32).unsqueeze(1)

    # Initialize model
    weights_path = os.path.join(persona_dir, 'model', 'linker_weights.pt')
    model = MemoryLinker()
    if os.path.exists(weights_path):
        model.load_state_dict(torch.load(weights_path, map_location='cpu', weights_only=True))
        print("Loaded existing weights (fine-tuning)", file=sys.stderr)
    else:
        model = initialize_weights(model)
        print("Cold start initialization", file=sys.stderr)

    # Training loop
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=1e-5)
    criterion = nn.BCELoss()

    # Class weight to handle imbalance
    if n_neg > 0 and n_pos > 0:
        pos_weight = n_neg / n_pos
        weight_tensor = torch.where(label_tensor > 0.5,
                                    torch.tensor(pos_weight),
                                    torch.tensor(1.0))
    else:
        weight_tensor = torch.ones_like(label_tensor)

    criterion_weighted = nn.BCELoss(weight=weight_tensor)

    dataset_size = len(pairs)
    batch_size = min(64, dataset_size)
    best_loss = float('inf')
    patience = 5
    patience_counter = 0

    model.train()
    for epoch in range(epochs):
        # Shuffle
        perm = torch.randperm(dataset_size)
        ctx_shuffled = ctx_tensor[perm]
        mem_shuffled = mem_tensor[perm]
        lbl_shuffled = label_tensor[perm]
        wgt_shuffled = weight_tensor[perm]

        epoch_loss = 0.0
        n_batches = 0

        for start in range(0, dataset_size, batch_size):
            end = min(start + batch_size, dataset_size)
            ctx_batch = ctx_shuffled[start:end]
            mem_batch = mem_shuffled[start:end]
            lbl_batch = lbl_shuffled[start:end]
            wgt_batch = wgt_shuffled[start:end]

            pred = model(ctx_batch, mem_batch)
            loss = nn.functional.binary_cross_entropy(pred, lbl_batch, weight=wgt_batch)

            optimizer.zero_grad()
            loss.backward()
            optimizer.step()

            epoch_loss += loss.item()
            n_batches += 1

        avg_loss = epoch_loss / n_batches

        # Early stopping
        if avg_loss < best_loss - 1e-4:
            best_loss = avg_loss
            patience_counter = 0
            best_state = {k: v.clone() for k, v in model.state_dict().items()}
        else:
            patience_counter += 1

        if (epoch + 1) % 5 == 0 or epoch == 0:
            print(f"  Epoch {epoch+1}/{epochs}  loss={avg_loss:.4f}  best={best_loss:.4f}", file=sys.stderr)

        if patience_counter >= patience:
            print(f"  Early stopping at epoch {epoch+1}", file=sys.stderr)
            break

    # Restore best weights
    if 'best_state' in dir():
        model.load_state_dict(best_state)

    # Evaluate
    model.eval()
    with torch.no_grad():
        all_preds = model(ctx_tensor, mem_tensor)
        pred_labels = (all_preds > 0.5).float()
        accuracy = (pred_labels == label_tensor).float().mean().item()

        # Per-class metrics
        tp = ((pred_labels == 1) & (label_tensor == 1)).sum().item()
        fp = ((pred_labels == 1) & (label_tensor == 0)).sum().item()
        fn = ((pred_labels == 0) & (label_tensor == 1)).sum().item()
        tn = ((pred_labels == 0) & (label_tensor == 0)).sum().item()

        precision = tp / (tp + fp) if (tp + fp) > 0 else 0
        recall = tp / (tp + fn) if (tp + fn) > 0 else 0
        f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0

    # Save
    os.makedirs(os.path.join(persona_dir, 'model'), exist_ok=True)
    torch.save(model.state_dict(), weights_path)

    # Save training metadata
    meta_out = {
        "status": "ok",
        "training_pairs": len(pairs),
        "positive": n_pos,
        "negative": n_neg,
        "feedback_entries": len(entries),
        "epochs_run": epoch + 1,
        "best_loss": round(best_loss, 4),
        "accuracy": round(accuracy, 4),
        "precision": round(precision, 4),
        "recall": round(recall, 4),
        "f1": round(f1, 4),
        "confusion": {"tp": int(tp), "fp": int(fp), "fn": int(fn), "tn": int(tn)},
        "weights_path": weights_path,
    }

    train_meta_path = os.path.join(persona_dir, 'model', 'train_meta.json')
    with open(train_meta_path, 'w') as f:
        json.dump(meta_out, f, indent=2)

    print(json.dumps(meta_out, indent=2))


def show_info(persona_dir):
    """Show training data statistics without training."""
    entries = load_feedback_log(persona_dir)

    meta_path = os.path.join(persona_dir, 'index_meta.json')
    id_to_idx = {}
    if os.path.exists(meta_path):
        with open(meta_path, 'r') as f:
            metas = json.load(f)
        id_to_idx = {m['id']: i for i, m in enumerate(metas)}

    pairs = build_training_pairs(entries, metas if id_to_idx else [], id_to_idx)
    n_pos = sum(1 for _, _, l in pairs if l > 0.5)
    n_neg = len(pairs) - n_pos

    weights_path = os.path.join(persona_dir, 'model', 'linker_weights.pt')
    train_meta_path = os.path.join(persona_dir, 'model', 'train_meta.json')

    last_train = None
    if os.path.exists(train_meta_path):
        with open(train_meta_path, 'r') as f:
            last_train = json.load(f)

    print(json.dumps({
        "feedback_entries": len(entries),
        "training_pairs": len(pairs),
        "positive": n_pos,
        "negative": n_neg,
        "weights_exist": os.path.exists(weights_path),
        "last_training": last_train,
    }, indent=2))


if __name__ == '__main__':
    parser = argparse.ArgumentParser(description='Train MemoryLinker from feedback logs')
    parser.add_argument('persona_dir', help='Path to persona directory')
    parser.add_argument('--epochs', type=int, default=20, help='Max training epochs')
    parser.add_argument('--lr', type=float, default=1e-3, help='Learning rate')
    parser.add_argument('--min-samples', type=int, default=20, help='Minimum pairs to start training')
    parser.add_argument('--info', action='store_true', help='Show stats without training')

    args = parser.parse_args()

    if args.info:
        show_info(args.persona_dir)
    else:
        train(args.persona_dir, epochs=args.epochs, lr=args.lr, min_samples=args.min_samples)
